// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as AssetStatusVariants from './asset_status_variants'

// The tagged union or sum type for the algebraic type `AssetStatus`.
export type AssetStatus = AssetStatusVariants.InUse |
  AssetStatusVariants.Maintenance |
  AssetStatusVariants.Broken;

// A value with helper functions to construct the type.
export const AssetStatus = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  InUse: { tag: "InUse" } as const,
  Maintenance: { tag: "Maintenance" } as const,
  Broken: { tag: "Broken" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "InUse", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Maintenance", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Broken", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AssetStatus): void {
      __AlgebraicTypeValue.serializeValue(writer, AssetStatus.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AssetStatus {
      return __AlgebraicTypeValue.deserializeValue(reader, AssetStatus.getTypeScriptAlgebraicType());
  },

}

export default AssetStatus;


