// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as DiscountTypeVariants from './discount_type_variants'

// The tagged union or sum type for the algebraic type `DiscountType`.
export type DiscountType = DiscountTypeVariants.Percentage |
  DiscountTypeVariants.FixedAmount;

// A value with helper functions to construct the type.
export const DiscountType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Percentage: { tag: "Percentage" } as const,
  FixedAmount: { tag: "FixedAmount" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Percentage", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "FixedAmount", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: DiscountType): void {
      __AlgebraicTypeValue.serializeValue(writer, DiscountType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): DiscountType {
      return __AlgebraicTypeValue.deserializeValue(reader, DiscountType.getTypeScriptAlgebraicType());
  },

}

export default DiscountType;


