// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

import { SaleItemInput } from "./sale_item_input_type";
// Mark import as potentially unused
declare type __keep_SaleItemInput = SaleItemInput;
import { PaymentMethod } from "./payment_method_type";
// Mark import as potentially unused
declare type __keep_PaymentMethod = PaymentMethod;

export type RecordSale = {
  outletId: bigint,
  items: SaleItemInput[],
  paymentMethod: PaymentMethod,
  date: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const RecordSale = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "outletId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "items", algebraicType: __AlgebraicTypeValue.Array(SaleItemInput.getTypeScriptAlgebraicType())},
        { name: "paymentMethod", algebraicType: PaymentMethod.getTypeScriptAlgebraicType()},
        { name: "date", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: RecordSale): void {
    __AlgebraicTypeValue.serializeValue(writer, RecordSale.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): RecordSale {
    return __AlgebraicTypeValue.deserializeValue(reader, RecordSale.getTypeScriptAlgebraicType());
  },

}

export default RecordSale;

