// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type RequestDistribution = {
  fromOutletId: bigint,
  toOutletId: bigint,
  ingredientId: bigint,
  quantity: bigint,
  date: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const RequestDistribution = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "fromOutletId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "toOutletId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "ingredientId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "quantity", algebraicType: __AlgebraicTypeValue.I64},
        { name: "date", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: RequestDistribution): void {
    __AlgebraicTypeValue.serializeValue(writer, RequestDistribution.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): RequestDistribution {
    return __AlgebraicTypeValue.deserializeValue(reader, RequestDistribution.getTypeScriptAlgebraicType());
  },

}

export default RequestDistribution;

