// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { PaymentMethod } from "./payment_method_type";
// Mark import as potentially unused
declare type __keep_PaymentMethod = PaymentMethod;


export type Sale = {
  id: bigint,
  outletId: bigint,
  total: bigint,
  paymentMethod: PaymentMethod,
  date: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const Sale = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "outletId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "total", algebraicType: __AlgebraicTypeValue.I64},
        { name: "paymentMethod", algebraicType: PaymentMethod.getTypeScriptAlgebraicType()},
        { name: "date", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: Sale): void {
    __AlgebraicTypeValue.serializeValue(writer, Sale.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Sale {
    return __AlgebraicTypeValue.deserializeValue(reader, Sale.getTypeScriptAlgebraicType());
  },

}

export default Sale;


