// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ShiftStatus } from "./shift_status_type";
// Mark import as potentially unused
declare type __keep_ShiftStatus = ShiftStatus;


export type ShiftReport = {
  id: bigint,
  outletId: bigint,
  employeeId: bigint,
  shiftStart: __Timestamp,
  shiftEnd: __Timestamp,
  initialCash: bigint,
  finalCash: bigint,
  status: ShiftStatus,
};
/**
 * An object for generated helper functions.
 */
export const ShiftReport = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "outletId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "employeeId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "shiftStart", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "shiftEnd", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "initialCash", algebraicType: __AlgebraicTypeValue.I64},
        { name: "finalCash", algebraicType: __AlgebraicTypeValue.I64},
        { name: "status", algebraicType: ShiftStatus.getTypeScriptAlgebraicType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ShiftReport): void {
    __AlgebraicTypeValue.serializeValue(writer, ShiftReport.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ShiftReport {
    return __AlgebraicTypeValue.deserializeValue(reader, ShiftReport.getTypeScriptAlgebraicType());
  },

}

export default ShiftReport;


