// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

import { OutletStatus } from "./outlet_status_type";
// Mark import as potentially unused
declare type __keep_OutletStatus = OutletStatus;

export type UpdateOutlet = {
  id: bigint,
  name: string,
  area: string,
  address: string,
  status: OutletStatus,
};
/**
 * An object for generated helper functions.
 */
export const UpdateOutlet = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "area", algebraicType: __AlgebraicTypeValue.String},
        { name: "address", algebraicType: __AlgebraicTypeValue.String},
        { name: "status", algebraicType: OutletStatus.getTypeScriptAlgebraicType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: UpdateOutlet): void {
    __AlgebraicTypeValue.serializeValue(writer, UpdateOutlet.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): UpdateOutlet {
    return __AlgebraicTypeValue.deserializeValue(reader, UpdateOutlet.getTypeScriptAlgebraicType());
  },

}

export default UpdateOutlet;

