// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as UserRoleVariants from './user_role_variants'

// The tagged union or sum type for the algebraic type `UserRole`.
export type UserRole = UserRoleVariants.AdminPusat |
  UserRoleVariants.AreaManager |
  UserRoleVariants.OutletManager |
  UserRoleVariants.Kasir |
  UserRoleVariants.Hr |
  UserRoleVariants.Gudang |
  UserRoleVariants.Finance;

// A value with helper functions to construct the type.
export const UserRole = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  AdminPusat: { tag: "AdminPusat" } as const,
  AreaManager: { tag: "AreaManager" } as const,
  OutletManager: { tag: "OutletManager" } as const,
  Kasir: { tag: "Kasir" } as const,
  HR: { tag: "HR" } as const,
  Gudang: { tag: "Gudang" } as const,
  Finance: { tag: "Finance" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "AdminPusat", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AreaManager", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "OutletManager", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Kasir", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "HR", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Gudang", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Finance", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: UserRole): void {
      __AlgebraicTypeValue.serializeValue(writer, UserRole.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): UserRole {
      return __AlgebraicTypeValue.deserializeValue(reader, UserRole.getTypeScriptAlgebraicType());
  },

}

export default UserRole;


